/**
 * Data model + YAML builder for interactive setup (`--setup`).
 */

import { stringify } from 'yaml'

import type { FixerConfig } from '@/types'

/** Checkbox values aligned with FixerConfig keys */
export const SETUP_FIXER_VALUES = {
  CURLY_BRACES: 'curlyBraces',
  ESLINT: 'eslint',
  JSON_VALIDATOR: 'jsonValidator',
  PRETTIER: 'prettier',
  SINGLE_LINE_ARROW: 'singleLineArrow'
} as const

export interface SetupWizardModel {
  enableI18nRules: boolean
  fixers: FixerConfig
  outputPath: string
  phase1Timeout: number
  phase2Timeout: number
  projectRoot: string
  sonar?: {
    hostUrl: string
    projectKey: string
  }
}

export function fixersFromSelection(selected: readonly string[]): FixerConfig {
  const set = new Set(selected)

  return {
    curlyBraces: set.has(SETUP_FIXER_VALUES.CURLY_BRACES),
    eslint: set.has(SETUP_FIXER_VALUES.ESLINT),
    jsonValidator: set.has(SETUP_FIXER_VALUES.JSON_VALIDATOR),
    prettier: set.has(SETUP_FIXER_VALUES.PRETTIER),
    singleLineArrow: set.has(SETUP_FIXER_VALUES.SINGLE_LINE_ARROW)
  }
}

interface QualityGateYamlDoc {
  enableI18nRules: boolean
  fixers: FixerConfig
  phase1Timeout: number
  phase2Timeout: number
  projectRoot: string
  sonar?: {
    hostUrl: string
    projectKey: string
  }
}

/**
 * Build YAML document for `.quality-gate.yaml` (used by wizard and tests).
 */
export function buildQualityGateYamlFromModel(model: SetupWizardModel): string {
  const doc: QualityGateYamlDoc = {
    enableI18nRules: model.enableI18nRules,
    fixers: model.fixers,
    phase1Timeout: model.phase1Timeout,
    phase2Timeout: model.phase2Timeout,
    projectRoot: model.projectRoot
  }

  if (model.sonar !== undefined) {
    doc.sonar = {
      hostUrl: model.sonar.hostUrl,
      projectKey: model.sonar.projectKey
    }
  }

  const header =
    '# AI Quality Gate — generated by `ai-quality-gate --setup`\n' +
    '# SonarQube: set SONAR_TOKEN in the environment (do not commit secrets).\n\n'

  return `${header}${stringify(doc, { lineWidth: 100 })}`
}
