/**
 * `QualityError.code` values other than the verification ones in `./verification`.
 */

export const ERROR_CODE = {
  CONFIG_INVALID: 'CONFIG_INVALID',
  PERSISTENT_FAILURE: 'PERSISTENT_FAILURE',
  ROLLBACK_FAILED: 'ROLLBACK_FAILED',
  SONAR_API_ERROR: 'SONAR_API_ERROR',
  SONAR_CONNECTION_FAILED: 'SONAR_CONNECTION_FAILED',
  SONAR_SCANNER_NOT_FOUND: 'SONAR_SCANNER_NOT_FOUND',
  SONAR_TIMEOUT: 'SONAR_TIMEOUT',
  TRANSFORM_FAILED: 'TRANSFORM_FAILED',
  TSCONFIG_NOT_FOUND: 'TSCONFIG_NOT_FOUND',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
  VERIFICATION_FAILED: 'VERIFICATION_FAILED'
} as const
